"""Assemble the final PRISMA-compliant manuscript and machine-readable artefacts."""
from __future__ import annotations

import csv
import io
import json
from pathlib import Path

from . import latex as _latex
from .agents.reporter import PRISMAReporter
from .models import ReviewState
from .prisma import checklist_markdown, mermaid_flow


def _strategy_table(state: ReviewState) -> str:
    rows = ["| Database | Query | Rationale |", "|----------|-------|-----------|"]
    for q in state.strategy.queries:
        rows.append(f"| {q.source} | `{q.query}` | {q.rationale} |")
    return "\n".join(rows)


def _characteristics_table(state: ReviewState) -> str:
    rows = ["| Study | Design | n | Population | Intervention | Comparator | RoB |",
            "|-------|--------|---|------------|--------------|------------|-----|"]
    rob = {r.uid: r.overall for r in state.rob}
    for ex in state.extractions:
        rows.append(
            f"| {ex.study_label} | {ex.design or '—'} | {ex.sample_size or '—'} | "
            f"{(ex.population or '—')[:40]} | {(ex.intervention or '—')[:30]} | "
            f"{(ex.comparator or '—')[:25]} | {rob.get(ex.uid, '—')} |"
        )
    return "\n".join(rows)


def _rob_table(state: ReviewState) -> str:
    if not state.rob:
        return "_No included studies appraised._"
    domains = [d.name for d in state.rob[0].domains]
    header = "| Study | " + " | ".join(domains) + " | Overall |"
    sep = "|" + "---|" * (len(domains) + 2)
    rows = [header, sep]
    for a in state.rob:
        jud = {d.name: d.judgement for d in a.domains}
        rows.append("| " + a.study_label + " | " +
                    " | ".join(jud.get(d, "—") for d in domains) + f" | {a.overall} |")
    return "\n".join(rows)


def _forest_table(state: ReviewState) -> str:
    meta = state.synthesis.meta_analysis
    if not meta or not meta.forest:
        return "_Meta-analysis not performed._"
    rows = [f"| Study | {meta.measure} | 95% CI | Weight % |",
            "|-------|------|--------|----------|"]
    for f in meta.forest:
        rows.append(f"| {f['study']} | {f['estimate']} | "
                    f"[{f['ci_lower']}, {f['ci_upper']}] | {f['weight_pct']} |")
    rows.append(f"| **Pooled ({meta.model})** | **{meta.pooled_estimate}** | "
                f"**[{meta.ci_lower}, {meta.ci_upper}]** | 100 |")
    return "\n".join(rows)


def _pub_bias_line(state: ReviewState) -> str:
    meta = state.synthesis.meta_analysis
    if not meta or meta.eggers_p is None:
        return ("Not formally tested (fewer than three studies with usable "
                "variances); a funnel plot is provided in the LaTeX paper where applicable.")
    asym = "evidence of" if meta.eggers_p < 0.10 else "no strong evidence of"
    power = " (under-powered, k<10)" if (meta.eggers_k or 0) < 10 else ""
    return (f"Egger's test: {asym} funnel asymmetry "
            f"(intercept={meta.eggers_intercept}, p={meta.eggers_p}, k={meta.eggers_k}){power}. "
            f"See the funnel plot in `paper.tex`.")


def _references(state: ReviewState) -> str:
    included = {u for u in state.included_studies}
    by_uid = {r.uid: r for r in state.unique_records}
    lines = []
    for i, uid in enumerate(state.included_studies, 1):
        r = by_uid.get(uid)
        if r:
            doi = f" https://doi.org/{r.doi}" if r.doi else ""
            lines.append(f"{i}. {r.citation()}.{doi}")
    return "\n".join(lines) or "_No included studies._"


def build_markdown(state: ReviewState, prose: dict[str, str]) -> str:
    p = state.protocol
    flow = state.prisma
    meta = state.synthesis.meta_analysis
    coverage = PRISMAReporter.coverage_map()

    results_line = (
        f"{len(state.included_studies)} studies were included. "
        + (f"The pooled {meta.measure} ({meta.model}-effects) was {meta.pooled_estimate} "
           f"(95% CI {meta.ci_lower} to {meta.ci_upper}; I²={meta.i_squared}%, "
           f"k={meta.k_studies}). {meta.interpretation}"
           if meta else "A meta-analysis was not performed due to insufficient comparable data.")
    )

    md = f"""# {p.title or 'Systematic Review'}

> Auto-generated by **NeuroAIon** — a PRISMA 2020-compliant, ten-agent systematic review engine.
> Model: `{state.model}`{' (MOCK / offline demo)' if state.mock else ''} · Run: `{state.run_id}` · {state.created_at}

**Review question.** {p.question}

**Registration.** {p.registration}

---

## Abstract

{prose.get('abstract', '').strip() or results_line}

---

## 1. Background

{prose.get('background', '').strip() or '_(background)_'}

## 2. Methods

{prose.get('methods', '').strip() or '_(methods)_'}

### 2.1 Eligibility criteria (PRISMA 5)

**Inclusion**
{chr(10).join('- ' + c for c in p.inclusion_criteria) or '- (none)'}

**Exclusion**
{chr(10).join('- ' + c for c in p.exclusion_criteria) or '- (none)'}

### 2.2 Information sources & search strategy (PRISMA 6–7)

Databases searched ({p.search.date_from} → {p.search.date_to}): {', '.join(flow.records_identified) or ', '.join(p.search.sources)}.

{_strategy_table(state)}

### 2.3 Selection, extraction & appraisal (PRISMA 8–12)

Two independent screeners (Reviewer 1, Reviewer 2) assessed every record at title/abstract
level; conflicts were resolved by an adjudicating reviewer. Inter-rater agreement
(Cohen's κ) = **{state.cohen_kappa if state.cohen_kappa is not None else 'n/a'}**.
Eligible full texts were assessed against the protocol. Data were extracted into a
structured form and each included study was appraised with **{p.risk_of_bias.tool}**.

---

## 3. Results

### 3.1 Study selection (PRISMA 16) — flow diagram

{mermaid_flow(flow)}

{results_line}

### 3.2 Characteristics of included studies (PRISMA 17)

{_characteristics_table(state)}

### 3.3 Risk of bias within studies (PRISMA 18)

{_rob_table(state)}

### 3.4 Results of syntheses (PRISMA 19–20)

{_forest_table(state)}

{state.synthesis.narrative.strip()}

**Publication bias (PRISMA 14).** {_pub_bias_line(state)}

### 3.5 Certainty of evidence (GRADE, PRISMA 22)

**Certainty: {state.synthesis.grade_certainty or 'not rated'}.** {state.synthesis.grade_rationale}

---

## 4. Discussion

{prose.get('discussion', '').strip() or '_(discussion)_'}

**Limitations.** {state.synthesis.limitations or '_(see discussion)_'}

## 5. Conclusions

{prose.get('conclusions', '').strip() or '_(conclusions)_'}

---

## PRISMA 2020 checklist (27 items)

{checklist_markdown(coverage)}

## References (included studies)

{_references(state)}

---

## Other information

- **Funding (PRISMA 25).** No specific funding declared for this automated review.
- **Competing interests (PRISMA 26).** None declared.
- **Data & code availability (PRISMA 27).** All artefacts for this run are saved alongside
  this report (`state.json`, `included_studies.csv`, `extractions.json`, `prisma_flow.json`).
"""
    return md


def write_artifacts(out_dir: Path, state: ReviewState, prose: dict[str, str]) -> Path:
    """Write the manuscript and all machine-readable artefacts; return report path."""
    out_dir.mkdir(parents=True, exist_ok=True)

    report_path = out_dir / "report.md"
    report_path.write_text(build_markdown(state, prose), encoding="utf-8")

    # Browser-friendly self-contained HTML (inline SVG figures).
    from . import html_report
    (out_dir / "review.html").write_text(
        html_report.build_html(state, prose), encoding="utf-8")

    (out_dir / "state.json").write_text(state.model_dump_json(indent=2), encoding="utf-8")
    (out_dir / "prisma_flow.json").write_text(
        state.prisma.model_dump_json(indent=2), encoding="utf-8")
    (out_dir / "extractions.json").write_text(
        json.dumps([e.model_dump() for e in state.extractions], indent=2), encoding="utf-8")

    # Included studies CSV.
    by_uid = {r.uid: r for r in state.unique_records}
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["uid", "citation", "doi", "source", "year"])
    for uid in state.included_studies:
        r = by_uid.get(uid)
        if r:
            w.writerow([uid, r.citation(), r.doi, r.source, r.year])
    (out_dir / "included_studies.csv").write_text(buf.getvalue(), encoding="utf-8")

    # PROSPERO registration export (PRISMA item 24).
    if state.protocol.prospero_export:
        from . import prospero
        (out_dir / "prospero_registration.md").write_text(
            prospero.build_registration(state), encoding="utf-8")

    return report_path


def write_latex(out_dir: Path, state: ReviewState, prose: dict[str, str]) -> Path:
    """Write the self-contained LaTeX paper and its bibliography. Returns the .tex path."""
    out_dir.mkdir(parents=True, exist_ok=True)
    tex, bib = _latex.build_document(state, prose)
    tex_path = out_dir / "paper.tex"
    tex_path.write_text(tex, encoding="utf-8")
    (out_dir / "references.bib").write_text(bib, encoding="utf-8")
    return tex_path


def compile_pdf(tex_path: Path) -> Path | None:
    """Best-effort PDF compilation if a TeX engine is available; else None."""
    import shutil
    import subprocess

    engine = shutil.which("latexmk") or shutil.which("pdflatex")
    if not engine:
        return None
    cwd = tex_path.parent
    try:
        if engine.endswith("latexmk"):
            cmd = [engine, "-pdf", "-interaction=nonstopmode", "-halt-on-error", tex_path.name]
            subprocess.run(cmd, cwd=cwd, capture_output=True, timeout=300)
        else:
            for _ in range(3):  # pdflatex + bibtex + pdflatex + pdflatex
                subprocess.run([engine, "-interaction=nonstopmode", "-halt-on-error",
                                tex_path.name], cwd=cwd, capture_output=True, timeout=300)
                subprocess.run(["bibtex", tex_path.stem], cwd=cwd, capture_output=True, timeout=120)
    except Exception:  # noqa: BLE001
        return None
    pdf = tex_path.with_suffix(".pdf")
    return pdf if pdf.exists() else None
