"""Protocol-setup interface.

A framework-agnostic wizard: the user sets the topic, the review framework
(PICO / PECO / SPIDER / PCC / …), its elements, eligibility criteria, sources,
the risk-of-bias tool, the citation style and every other protocol choice. The
answers are written to a ``protocol.yaml`` that the pipeline then runs.

Two entry points:
  • ``build_seed(...)``  — programmatic / testable construction of the protocol seed
  • ``interactive(...)`` — terminal prompts (used by ``neuroaion new``)
"""
from __future__ import annotations

from pathlib import Path
from typing import Optional

import yaml

from . import frameworks
from .sources.registry import SOURCES

# Map common element labels onto the canonical synthesis slots (keeps meta-analysis
# / PROSPERO working regardless of framework).
_POP = {"population", "sample", "condition", "client", "patient"}
_INT = {"intervention", "exposure", "index test", "phenomenon of interest", "concept"}
_CMP = {"comparator", "comparison", "reference test", "perspective"}
_OUT = {"outcome", "evaluation", "diagnosis", "impact"}


def build_seed(
    *, topic: str, framework: str = "PICO", elements: Optional[dict] = None,
    question: str = "auto", designs: Optional[list[str]] = None,
    inclusion: Optional[list[str]] = None, exclusion: Optional[list[str]] = None,
    sources: Optional[list[str]] = None, date_from: str = "2010-01-01",
    date_to: str = "auto", languages: Optional[list[str]] = None,
    keywords: Optional[list[list[str]]] = None, max_per_source: int = 200,
    import_files: Optional[list[str]] = None, deep_pagination: bool = False,
    snowball: bool = False, snowball_max: int = 200, fulltext_dir: str = "",
    effect_measure: str = "SMD", synthesis_model: str = "random",
    publication_bias: bool = True, rob_tool: str = "RoB2",
    citation_style: str = "vancouver", registration: str = "Not registered",
    contact: str = "", prospero_export: bool = True,
) -> dict:
    """Assemble a protocol seed dict (the schema the pipeline consumes)."""
    framework = frameworks.normalize_framework(framework)
    elements = elements or {}
    # Canonical slots for synthesis/PROSPERO, inferred from the framework elements.
    pop = inter = comp = outc = ""
    for label, val in elements.items():
        low = label.strip().lower()
        if low in _POP and not pop:
            pop = val
        elif low in _INT and not inter:
            inter = val
        elif low in _CMP and not comp:
            comp = val
        elif low in _OUT and not outc:
            outc = val

    pico = {
        "framework": framework, "elements": elements,
        "population": pop, "intervention": inter, "comparator": comp, "outcome": outc,
        "study_designs": designs or frameworks.DEFAULT_DESIGNS.get(framework, ["any"]),
    }
    return {
        "title": topic,
        "question": question,
        "pico": pico,
        "inclusion_criteria": inclusion or [],
        "exclusion_criteria": exclusion or [],
        "search": {
            "sources": sources or list(frameworks.DEFAULT_SOURCES),
            "date_from": date_from, "date_to": date_to,
            "languages": languages or ["en"], "max_records_per_source": max_per_source,
            "keywords": keywords or [],
            # Recall amplifiers + subscription-database citation exports.
            "import_files": import_files or [],
            "deep_pagination": deep_pagination,
            "snowball": snowball, "snowball_max": snowball_max,
            "fulltext_dir": fulltext_dir,
        },
        "synthesis": {"effect_measure": effect_measure, "model": synthesis_model,
                      "min_studies_for_meta": 2, "publication_bias": publication_bias},
        "risk_of_bias": {"tool": rob_tool, "grade": True},
        "reporting": {"authors_contact": contact, "registration": registration,
                      "prospero_export": prospero_export, "citation_style": citation_style},
    }


def write_protocol_yaml(seed: dict, path: str | Path) -> Path:
    path = Path(path).expanduser()
    path.parent.mkdir(parents=True, exist_ok=True)
    header = ("# NeuroAIon protocol — generated by the setup wizard.\n"
              "# Edit freely; re-run with:  neuroaion run -p <this file> --out <folder>\n\n")
    path.write_text(header + yaml.safe_dump(seed, sort_keys=False, allow_unicode=True),
                    encoding="utf-8")
    return path


# ── Interactive terminal interface ───────────────────────────────────────────
def _ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    val = input(f"{prompt}{suffix}: ").strip()
    return val or default


def _choose(prompt: str, options: list[str], default: str) -> str:
    print(f"\n{prompt}")
    for i, o in enumerate(options, 1):
        mark = " (default)" if o == default else ""
        print(f"  {i}. {o}{mark}")
    raw = input(f"Choose 1-{len(options)} [{default}]: ").strip()
    if not raw:
        return default
    if raw.isdigit() and 1 <= int(raw) <= len(options):
        return options[int(raw) - 1]
    return raw if raw in options else default


def _multi(prompt: str, options: list[str], default: list[str]) -> list[str]:
    print(f"\n{prompt} (comma-separated numbers; Enter = default)")
    for i, o in enumerate(options, 1):
        print(f"  {i}. {o}")
    raw = input(f"[{', '.join(default)}]: ").strip()
    if not raw:
        return default
    picked = []
    for tok in raw.split(","):
        tok = tok.strip()
        if tok.isdigit() and 1 <= int(tok) <= len(options):
            picked.append(options[int(tok) - 1])
        elif tok in options:
            picked.append(tok)
    return picked or default


def _ask_lines(prompt: str) -> list[str]:
    print(f"\n{prompt} (one per line; blank line to finish)")
    out = []
    while True:
        line = input("  - ").strip()
        if not line:
            break
        out.append(line)
    return out


def interactive() -> tuple[dict, str, bool]:
    """Run the terminal wizard. Returns (seed, output_path, run_now)."""
    print("\n══════════════════════════════════════════════════════════")
    print("  NeuroAIon — systematic review setup")
    print("══════════════════════════════════════════════════════════")

    out_path = _ask("\nOutput folder (paste the path where everything is saved)",
                    str(Path.cwd() / "review"))
    topic = _ask("\nReview topic / working title")
    question = _ask("Review question (or 'auto' to draft it)", "auto")

    fw = _choose("Review framework", list(frameworks.FRAMEWORKS), "PICO")
    print(f"\nDefine the {fw} elements:")
    elements = {}
    for label in frameworks.framework_elements(fw):
        elements[label] = _ask(f"  {label}")

    designs = _ask("\nEligible study designs (comma-separated)",
                   ", ".join(frameworks.DEFAULT_DESIGNS.get(fw, ["any"])))
    designs = [d.strip() for d in designs.split(",") if d.strip()]

    inclusion = _ask_lines("Inclusion criteria")
    exclusion = _ask_lines("Exclusion criteria")

    sources = _multi("Databases to search (free APIs)", list(SOURCES),
                     list(frameworks.DEFAULT_SOURCES))
    date_from = _ask("\nSearch from (YYYY-MM-DD)", "2010-01-01")
    date_to = _ask("Search to (YYYY-MM-DD or 'auto')", "auto")

    # Recall amplifiers.
    print("\n── Recall (the make-or-break of a systematic review) ──")
    print("For subscription databases (Scopus, Web of Science, Ovid, EBSCO …) run the")
    print("search in your own browser, export the results (RIS/BibTeX/NBIB/EndNote/CSV),")
    print("and list the files here — no credentials are ever used by the engine.")
    import_files = _ask_lines("Citation-export files to import (paths)")
    deep_pagination = _ask("Deep pagination — fetch beyond the first page? (y/N)",
                           "N").lower().startswith("y")
    snowball = _ask("Citation snowballing — chase references + cited-by? (y/N)",
                    "N").lower().startswith("y")
    snowball_max = 200
    if snowball:
        sm = _ask("  Max records to add via snowballing", "200")
        snowball_max = int(sm) if sm.isdigit() else 200
    print("\nDrop the full-text PDFs you obtained via your own access into a folder;")
    print("they are parsed (text + tables + references + statistics) and used as the")
    print("working full text for screening, extraction and risk of bias.")
    fulltext_dir = _ask("Folder of full-text PDFs (optional)", "")

    measure = _choose("Effect measure", ["SMD", "MD", "OR", "RR", "HR"], "SMD")
    model = _choose("Meta-analysis model", ["random", "fixed"], "random")
    rob = _choose("Risk-of-bias tool", list(frameworks.ROB_TOOLS), "RoB2")
    citation = _choose("Citation style", frameworks.CITATION_STYLES, "vancouver")

    registration = _ask("\nRegistration (e.g. PROSPERO ID, or 'Not registered')",
                        "Not registered")
    contact = _ask("Contact email", "")

    seed = build_seed(
        topic=topic, framework=fw, elements=elements, question=question,
        designs=designs, inclusion=inclusion, exclusion=exclusion, sources=sources,
        date_from=date_from, date_to=date_to, import_files=import_files,
        deep_pagination=deep_pagination, snowball=snowball, snowball_max=snowball_max,
        fulltext_dir=fulltext_dir,
        effect_measure=measure, synthesis_model=model, rob_tool=rob,
        citation_style=citation, registration=registration, contact=contact,
    )
    run_now = _ask("\nRun the review now? (y/N)", "N").lower().startswith("y")
    return seed, out_path, run_now
